// AUTO-GENERATED from the legacy site's projects/operator.html (wizzy22-lab/Wizzy).
// Every EN/KO string from the original case study is preserved here verbatim.
// Regenerate rather than hand-editing structure; hand-edits to copy are fine.

import type { CaseStudy } from "./types";

export const operatorCaseStudy: CaseStudy = {
  slug: "operator",
  hero: {
    image: "/projects/operator/hero-mockup.jpg",
    tag: { en: "UX / Product Design · Energy Management", ko: "UX / 프로덕트 디자인 · 에너지 관리" },
    headline: { en: "Without criteria, every HVAC decision relies on intuition", ko: "기준이 없으면, 모든 HVAC 결정은 직관에 의존한다" },
    description: { en: "Small business owners make HVAC decisions multiple times a day. But the system never tells them when to adjust, what to base it on, or what will happen after. This project gives them the information they need to decide — not just the controls to act.", ko: "자영업자는 하루에도 여러 번 냉난방 결정을 내린다. 하지만 시스템은 언제 조절해야 하는지, 무엇을 기준으로 판단해야 하는지, 그리고 그 결과가 어떻게 되는지 알려주지 않는다. 이 프로젝트는 단순한 제어 기능이 아니라, 결정을 위한 정보를 제공한다." },
    meta: [
      { label: { en: "Duration", ko: "기간" }, value: { en: "7 weeks", ko: "7주" } },
      { label: { en: "Project type", ko: "프로젝트 유형" }, value: { en: "Team project", ko: "팀 프로젝트" } },
      { label: { en: "Contribution", ko: "기여도" }, value: { en: "50%", ko: "50%" } },
      { label: { en: "Role", ko: "역할" }, value: { en: "Problem Framing & Research Lead\nUX Strategy & Concept Design\nData-driven UX & Communication Design\nProduct Perspective & Execution", ko: "문제 프레이밍 & 리서치 리드\nUX 전략 & 컨셉 디자인\n데이터 기반 UX & 커뮤니케이션 디자인\n제품 관점 & 실행" } },
      { label: { en: "Tools", ko: "툴" }, value: { en: "Figma · Figma Make", ko: "Figma · Figma Make" } },
    ],
  },
  sections: [
    {
      id: "overview",
      blocks: [
        { role: "groupLabel", text: { en: "Overview", ko: "개요" } },
        { role: "subLabel", text: { en: "Project Summary", ko: "프로젝트 요약" } },
        { role: "cardLabel", text: { en: "01 — How It Started", ko: "01 — 시작" } },
        { role: "cardBody", text: { en: "This project began with a question from a teammate.", ko: "이 프로젝트는 팀원의 질문에서 시작되었다" } },
        { role: "insight", text: { en: "\"Why do people adjust their HVAC systems on intuition — without any clear criteria?\"", ko: "\"왜 사람들은 냉난방을 명확한 기준 없이 감으로 조절하고 있을까?\"" } },
        { role: "cardLabel", text: { en: "02 — Defining the Target", ko: "02 — 타겟 설정" } },
        { role: "cardBody", text: { en: "We thought carefully about who this problem should be solved for.", ko: "우리는 이 문제를 누구에게 풀어야 할지 고민했고, 가정용이 아닌" } },
        { role: "insight", text: { en: "We set small business owners — not residential users — as our target.", ko: "Small business owner를 타겟으로 설정했다" } },
        { role: "cardLabel", text: { en: "03 — Personal Experience", ko: "03 — 개인 경험 연결" } },
        { role: "cardBody", text: { en: "Running my own store, I kept adjusting the HVAC — but without any clear criteria to guide me, I always fell back on intuition.", ko: "나는 실제 매장을 운영하며 냉난방을 계속 조절하지만 판단 기준 없이 직관에 의존하게 되는 문제를 겪고 있었다" } },
        { role: "cardLabel", text: { en: "04 — Redefining the Problem", ko: "04 — 문제 재정의" } },
        { role: "cardBody", text: { en: "We concluded that this was not simply a problem of control.", ko: "우리는 이 문제가 단순한 조작 문제가 아니라" } },
        { role: "insight", text: { en: "It was a problem of \"a structure where making a judgment is inherently difficult.\"", ko: "\"판단 자체가 어려운 구조\"의 문제라는 결론에 도달했다" } },
        { role: "cardLabel", text: { en: "05 — Solution Direction", ko: "05 — 해결 방향" } },
        { role: "cardBody", text: { en: "The answer wasn't to leave users to figure it out on their own.", ko: "이 문제는 사용자가 직접 판단하도록 두는 것이 아니라" } },
        { role: "insight", text: { en: "The system proposes the optimal choice first — and the user simply reviews and approves.", ko: "시스템이 먼저 최적의 선택을 제안하고, 사용자는 이를 확인하고 승인하는 구조로 전환해야 했다" } },
        { role: "body", text: { en: "We ran user research to validate this hypothesis.", ko: "이 가설을 검증하기 위해 사용자 리서치를 진행했다" } },
      ],
    },
    {
      id: "approach",
      blocks: [
        { role: "groupLabel", text: { en: "Approach", ko: "접근" } },
        { role: "subLabel", text: { en: "Secondary Research", ko: "2차 리서치" } },
        { role: "body", text: { en: "Analysis of user voices showed that operators were adjusting HVAC temperature and modes", ko: "사용자 보이스를 분석한 결과, 운영자는 냉난방 온도와 모드를" } },
        { role: "body", text: { en: "Categorizing review and community data showed", ko: "리뷰와 커뮤니티 데이터를 카테고리화한 결과," } },
        { role: "image", src: "/projects/operator/approach/secondary-research.jpg", alt: "Secondary Research" },
        // MISSING ASSET: approach/secondary-research-2.jpg — 404 on the legacy site too; re-export from Figma.
        { role: "subLabel", text: { en: "Primary Research", ko: "1차 리서치" } },
        { role: "image", src: "/projects/operator/approach/interview-protocol-en.jpg", alt: "Interview Protocol" },
        // MISSING ASSET: approach/interview-photo-1.jpg — 404 on the legacy site too; re-export from Figma.
        { role: "insight", text: { en: "• HVAC decision-making was happening — but the process was never learned from or accumulated", ko: "• 냉난방 의사결정은 존재하지만, 그 과정이 학습되거나 축적되지 않는 구조였다" } },
        { role: "insight", text: { en: "• Because outcomes are unpredictable, a cycle of intuition → adjustment → repetition forms", ko: "• 결과를 예측할 수 없기 때문에 '직관 → 조정 → 반복' 구조가 형성된다" } },
        { role: "subLabel", text: { en: "Analysis", ko: "분석" } },
        { role: "body", text: { en: "Structuring the interview data through affinity mapping and thematic analysis,", ko: "어피니티 매핑과 주제 분석을 통해 인터뷰 데이터를 구조화한 결과," } },
        { role: "body", text: { en: "Operators had no trouble operating the HVAC system itself — but", ko: "운영자들은 냉난방을 조작하는 데에는 어려움이 없었지만" } },
        { role: "listItem", text: { en: "When to adjust", ko: "언제 조절할지" } },
        { role: "listItem", text: { en: "How much to adjust", ko: "얼마나 조절할지" } },
        { role: "listItem", text: { en: "How to balance comfort against cost", ko: "쾌적함과 비용을 어떻게 균형 잡을지" } },
        { role: "image", src: "/projects/operator/approach/affinity-mapping.jpg", alt: "Affinity Mapping" },
        { role: "image", src: "/projects/operator/approach/thematic-analysis.jpg", alt: "Thematic Analysis" },
        { role: "subLabel", text: { en: "Context Research", ko: "맥락 리서치" } },
        { role: "h3", text: { en: "HVAC costs matter to small business owners — but the billing structure isn't being used as a decision criterion", ko: "냉난방 비용은 자영업자에게 중요한 변수지만, 과금구조는 판단 기준으로 사용되지 않는다" } },
        { role: "body", text: { en: "Interviews confirmed cost as a key variable, so we analyzed the electricity pricing structure. Energy rates vary significantly by time of day and usage —", ko: "인터뷰 과정에서 비용이 주요 변수임을 확인했고, 전기요금 구조를 분석했다. 에너지 요금은 시간대와 사용 조건에 따라 크게 달라진다 —" } },
        { role: "listItem", text: { en: "Peak / mid / off-peak hours", ko: "피크 / 중간 / 경부하 시간" } },
        { role: "listItem", text: { en: "Tiered pricing based on consumption", ko: "사용량에 따른 누진 구조" } },
        { role: "insight", text: { en: "→ but the structure is too complex to grasp intuitively", ko: "→이러한 정보는 직관적으로 이해하기 어려운 형태로 구성되어 있었다" } },
        { role: "body", text: { en: "As a result, even though operators considered cost, they had no way of knowing how each choice affected their actual bill —", ko: "그 결과, 운영자는 비용을 고려하고 있음에도 불구하고 각 선택이 실제 요금에 어떤 영향을 주는지 알 수 없어" } },
        { role: "insight", text: { en: "→ leaving cost as something they couldn't use as a decision criterion", ko: "→비용을 판단 기준으로 활용하지 못하고 있었다" } },
        { role: "cardLabel", text: { en: "Insight", ko: "인사이트" } },
        { role: "cardTitle", text: { en: "Cost is considered — but not used in decision-making", ko: "비용은 고려되지만, 의사결정에는 사용되지 않는다" } },
        { role: "cardBody", text: { en: "Operators care about cost — but because choices and outcomes aren't connected, cost functions not as a decision criterion but as information checked only after the fact", ko: "운영자는 비용을 중요하게 생각하지만, 선택과 결과가 연결되지 않기 때문에 비용은 결정을 돕는 기준이 아니라, 사후에 확인하는 정보로만 작동하고 있었다" } },
        { role: "image", src: "/projects/operator/approach/context-research.jpg", alt: "Context Research" },
        { role: "subLabel", text: { en: "Competitor Analysis", ko: "경쟁사 분석" } },
        { role: "h3", text: { en: "We analyzed existing HVAC and EMS systems", ko: "기존 HVAC와 EMS 시스템을 분석했다" } },
        { role: "cardLabel", text: { en: "What systems can do", ko: "기존 시스템 기능" } },
        { role: "cardBody", text: { en: "Direct control of temperature and mode · Energy usage data provided", ko: "온도와 모드를 직접 조절 가능 · 에너지 사용량 데이터 제공" } },
        { role: "cardLabel", text: { en: "What's missing", ko: "한계" } },
        { role: "cardBody", text: { en: "No way to see how each choice affects comfort and cost — users can't judge which option is better even with data", ko: "각 선택이 쾌적함과 비용에 어떤 영향을 주는지 알 수 없고, 데이터를 보더라도 어떤 선택이 더 나은지 판단할 수 없었다" } },
        { role: "image", src: "/projects/operator/approach/competitor-analysis.jpg", alt: "Competitor Analysis" },
        { role: "cardTitle", text: { en: "Existing systems have no link between choice and outcome", ko: "기존 시스템은 선택과 결과의 연결이 없다" } },
        { role: "subLabel", text: { en: "Define", ko: "Define" } },
        { role: "defineNum", text: { en: "01 — Problem Definition", ko: "01 — 문제 정의" } },
        { role: "defineBody", text: { en: "Small business owners can adjust their HVAC —", ko: "Small business owner는 냉난방을 조절할 수는 있지만," } },
        { role: "defineKey", text: { en: "they cannot make a genuine judgment without knowing the outcome of each choice.", ko: "각 선택의 결과를 알 수 없어 판단할 수 없다" } },
        { role: "defineBody", text: { en: "As a result", ko: "그 결과" } },
        { role: "body", text: { en: "They cannot compare comfort against cost", ko: "쾌적함과 비용을 비교하지 못하고" } },
        { role: "body", text: { en: "They end up repeating the same adjustments", ko: "동일한 조정을 반복하게 된다" } },
        { role: "image", src: "/projects/operator/define/persona.jpg", alt: "User Persona" },
        { role: "image", src: "/projects/operator/define/user-journey-map.jpg", alt: "User Journey Map" },
        { role: "defineNum", text: { en: "02 — Root Cause", ko: "02 — 근본 원인" } },
        { role: "defineBody", text: { en: "The problem isn't a lack of controls —", ko: "문제는 기능이 부족한 것이 아니라," } },
        { role: "defineKey", text: { en: "the structure never connects choices to their outcomes.", ko: "선택과 결과가 연결되지 않는 구조에 있다" } },
        { role: "defineBody", text: { en: "The system shows", ko: "시스템은" } },
        { role: "body", text: { en: "Action (temperature, mode)", ko: "행동 (온도, 모드)" } },
        { role: "body", text: { en: "Outcome (comfort, cost)", ko: "결과 (쾌적도, 비용)" } },
        { role: "defineBody", text: { en: "as separate things — so users can", ko: "를 분리해서 보여주기 때문에 — 사용자는" } },
        { role: "defineKey", text: { en: "neither compare nor learn.", ko: "비교도, 학습도 할 수 없다" } },
        { role: "diagramLabel", text: { en: "What the system shows", ko: "시스템이 보여주는 것" } },
        { role: "diagramLabel", text: { en: "Action", ko: "행동" } },
        { role: "diagramSub", text: { en: "Temperature · Mode", ko: "온도 · 모드" } },
        { role: "diagramSub", text: { en: "no connection", ko: "연결 없음" } },
        { role: "diagramLabel", text: { en: "Outcome", ko: "결과" } },
        { role: "diagramSub", text: { en: "Comfort · Cost", ko: "쾌적도 · 비용" } },
        { role: "diagramSub", text: { en: "→ Users cannot connect the two", ko: "→ 사용자는 둘을 연결할 수 없다" } },
        { role: "defineNum", text: { en: "03 — Behavior Insight", ko: "03 — 행동 인사이트" } },
        { role: "defineBody", text: { en: "Throughout the day, operators adjust HVAC across the flow of", ko: "운영자는 하루 동안" } },
        { role: "flowStep", text: { en: "Open", ko: "오픈" } },
        { role: "flowStep", text: { en: "Peak", ko: "피크" } },
        { role: "flowStep", text: { en: "Close", ko: "마감" } },
        { role: "defineBody", text: { en: "store operations — continuously.", ko: "흐름 속에서 냉난방을 지속적으로 조정한다." } },
        { role: "defineBody", text: { en: "Especially during peak hours —", ko: "특히 피크 시간에는 —" } },
        { role: "defineKey", text: { en: "speed of adjustment takes priority over deliberate judgment.", ko: "판단보다 빠른 조정이 우선된다" } },
        { role: "defineNum", text: { en: "04 — Final Definition", ko: "04 — 최종 정의" } },
        { role: "defineBody", text: { en: "Every moment, operators must choose between comfort and cost —", ko: "운영자는 매 순간 쾌적함과 비용 사이에서 선택해야 하지만," } },
        { role: "defineBody", text: { en: "→ without criteria or feedback to compare against, decisions repeat and never accumulate.", ko: "→ 비교할 기준과 피드백이 없어 결정이 반복되고 축적되지 않는다" } },
        { role: "subLabel", text: { en: "Ideate", ko: "Ideate" } },
        { role: "subLabel", text: { en: "Rather than presenting data to interpret, we designed a structure that proposes a choice.", ko: "데이터를 보여주는 것이 아니라, 선택을 제안하는 구조로 설계했다" } },
        { role: "defineNum", text: { en: "Solution Direction", ko: "솔루션 방향" } },
        { role: "defineBody", text: { en: "We shifted from showing HVAC data for users to interpret, to a structure where the system calculates the outcome of each option and presents a single optimal choice.", ko: "냉난방 데이터를 보여주는 것이 아니라, 시스템이 각 선택의 결과를 계산해 최적의 선택을 제안하는 구조로 전환했다." } },
        { role: "diagramLabel", text: { en: "Before", ko: "Before" } },
        { role: "body", text: { en: "User judges directly", ko: "사용자가 직접 판단" } },
        { role: "body", text: { en: "Outcome is unknown", ko: "결과를 알 수 없음" } },
        { role: "diagramLabel", text: { en: "After", ko: "After" } },
        { role: "body", text: { en: "System proposes the optimal choice", ko: "시스템이 최적 선택 제안" } },
        { role: "body", text: { en: "Outcome is shown alongside the choice", ko: "결과를 함께 제공" } },
        { role: "insightLabel", text: { en: "Core", ko: "핵심" } },
        { role: "insight", text: { en: "Judgment is not left to the user.", ko: "판단을 사용자에게 맡기지 않는다" } },
        { role: "defineNum", text: { en: "Decision Model", ko: "의사결정 모델" } },
        { role: "defineBody", text: { en: "HVAC decisions involve multiple variables acting simultaneously —", ko: "냉난방 판단은" } },
        { role: "defineBody", text: { en: "outdoor environment, store conditions, and cost.", ko: "외부 환경 / 매장 상태 / 비용 등 여러 변수가 동시에 작용하는 문제다." } },
        { role: "defineBody", text: { en: "We structured how each variable converts into comfort and cost impact,", ko: "각 요소를 쾌적도 / 비용 영향으로 변환하고," } },
        { role: "defineKey", text: { en: "then connected them into a single judgment.", ko: "하나의 판단으로 연결하는 구조를 설계했다" } },
        { role: "insightLabel", text: { en: "Core", ko: "핵심" } },
        { role: "insight", text: { en: "Complex variables → compressed into one choice.", ko: "복잡한 변수 → 하나의 선택으로 압축" } },
        { role: "image", src: "/projects/operator/ideate/functional-structure.jpg", alt: "Functional Categorization" },
        { role: "defineNum", text: { en: "Scenario + Prioritization", ko: "시나리오 + 우선순위" } },
        { role: "defineBody", text: { en: "Based on real store operations, we identified the key decision moments —", ko: "실제 매장 운영 상황을 기준으로 의사결정이 발생하는 핵심 순간을 정의했다 —" } },
        { role: "defineKey", text: { en: "then built the MVP around only what those moments required.", ko: "그 순간에 필요한 기능만 MVP로 남겼다" } },
        { role: "image", src: "/projects/operator/ideate/scenario.jpg", alt: "Scenario" },
        { role: "image", src: "/projects/operator/ideate/2x2-matrix.jpg", alt: "2x2 Matrix" },
        { role: "image", src: "/projects/operator/ideate/moscow.jpg", alt: "MoSCoW" },
        { role: "insightLabel", text: { en: "Core", ko: "핵심" } },
        { role: "insight", text: { en: "Not every possible feature — only those directly needed for real decision-making.", ko: "모든 기능이 아니라, 결정에 필요한 기능만 남겼다" } },
        { role: "defineNum", text: { en: "Ideation Process", ko: "아이디에이션 과정" } },
        { role: "defineBody", text: { en: "To explore multiple UI structures quickly, we ran Crazy 8 to experiment with different layouts.", ko: "다양한 UI 구조를 탐색하기 위해 Crazy 8을 통해 여러 레이아웃을 빠르게 실험했다." } },
        { role: "defineKey", text: { en: "Integrating judgment, choice, and outcome in one view proved most efficient.", ko: "여러 구조 중, 판단·선택·결과를 통합한 방식이 가장 효율적이었다" } },
        { role: "insightLabel", text: { en: "Core", ko: "핵심" } },
        { role: "insight", text: { en: "One screen. One decision. Judgment, choice, and outcome together.", ko: "한 화면에서 판단·선택·결과를 동시에 확인한다" } },
        { role: "defineNum", text: { en: "Integrated Flow", ko: "통합 흐름" } },
        { role: "defineBody", text: { en: "Rather than splitting judgment, choice, and outcome across separate steps,", ko: "판단 → 선택 → 결과를 분리하지 않고" } },
        { role: "defineKey", text: { en: "we integrated them into a single continuous flow.", ko: "하나의 흐름으로 통합했다" } },
        { role: "image", src: "/projects/operator/ideate/ia.jpg", alt: "Information Architecture" },
        { role: "image", src: "/projects/operator/ideate/system-flow.jpg", alt: "System Flow" },
        { role: "insightLabel", text: { en: "Core", ko: "핵심" } },
        { role: "insight", text: { en: "Information is not divided — it is grouped by decision unit.", ko: "정보를 나누지 않고, 결정 단위로 묶는다" } },
        { role: "defineNum", text: { en: "Wireframe", ko: "와이어프레임" } },
        { role: "defineBody", text: { en: "Current status, expected outcome, and recommended choice — all visible on a single screen.", ko: "현재 상태, 예상 결과, 추천 선택을 한 화면에서 동시에 확인할 수 있도록 설계했다." } },
        { role: "defineKey", text: { en: "One glance. One confirmation. Done.", ko: "한 번의 확인으로 바로 선택할 수 있는 구조" } },
        { role: "image", src: "/projects/operator/ideate/wireframe-1.jpg", alt: "Wireframe" },
        { role: "defineNum", text: { en: "Design System", ko: "디자인 시스템" } },
        { role: "defineBody", text: { en: "Status, outcome, and choice are visually separated so users can compare without interpretation.", ko: "사용자가 해석하지 않아도 되도록 정보를 비교 가능한 형태로 설계했다." } },
        { role: "defineKey", text: { en: "Designed to be understood at a glance — no interpretation required.", ko: "해석 없이 바로 이해할 수 있는 구조" } },
        { role: "image", src: "/projects/operator/ideate/design-system.jpg", alt: "Design System" },
      ],
    },
    {
      id: "solution",
      blocks: [
        { role: "groupLabel", text: { en: "Solution", ko: "솔루션" } },
        { role: "subLabel", text: { en: "Key Features", ko: "핵심 기능" } },
        { role: "h2", text: { en: "Three Features That Replace Repeated Adjustments with a Single Judgment", ko: "반복적인 조정을 한 번의 판단으로 전환하는 세 가지 기능" } },
        { role: "image", src: "/projects/operator/solution/feature-apply.jpg", alt: "Feature 01" },
        { role: "featureNum", text: { en: "FEATURE 01", ko: "기능 01" } },
        { role: "featureTitle", text: { en: "한 화면에서 판단과 선택을 동시에", ko: "한 화면에서 판단과 선택을 동시에" } },
        { role: "featureBody", text: { en: "현재 상태, 예상 결과(쾌적도·비용), 선택지를 👉 하나의 화면에 통합했다", ko: "현재 상태, 예상 결과(쾌적도·비용), 선택지를 👉 하나의 화면에 통합했다" } },
        { role: "featureBullet", text: { en: "정보 해석 없이 바로 선택 가능", ko: "정보 해석 없이 바로 선택 가능" } },
        { role: "resultLabel", text: { en: "결과", ko: "결과" } },
        { role: "resultBody", text: { en: "반복 조정 → 한 번의 판단으로 전환", ko: "반복 조정 → 한 번의 판단으로 전환" } },
        { role: "image", src: "/projects/operator/solution/feature-datalog.jpg", alt: "Feature 02" },
        { role: "featureNum", text: { en: "FEATURE 02", ko: "기능 02" } },
        { role: "featureTitle", text: { en: "선택의 결과를 기록하고 학습한다", ko: "선택의 결과를 기록하고 학습한다" } },
        { role: "featureBody", text: { en: "냉난방 조절 이력과 결과를 함께 기록하고 시각화했다", ko: "냉난방 조절 이력과 결과를 함께 기록하고 시각화했다" } },
        { role: "featureBullet", text: { en: "어떤 선택이 어떤 결과를 만들었는지 축적", ko: "어떤 선택이 어떤 결과를 만들었는지 축적" } },
        { role: "featureBullet", text: { en: "데이터 기반 판단 가능", ko: "데이터 기반 판단 가능" } },
        { role: "resultLabel", text: { en: "결과", ko: "결과" } },
        { role: "resultBody", text: { en: "같은 판단 반복 → 학습되는 의사결정 구조로 전환", ko: "같은 판단 반복 → 학습되는 의사결정 구조로 전환" } },
        { role: "image", src: "/projects/operator/solution/feature-scan.jpg", alt: "Feature 03" },
        { role: "featureNum", text: { en: "FEATURE 03", ko: "기능 03" } },
        { role: "featureTitle", text: { en: "반복되는 판단을 자동화한다", ko: "반복되는 판단을 자동화한다" } },
        { role: "featureBody", text: { en: "시간대·상황별 냉난방 기준을 미리 설정했다", ko: "시간대·상황별 냉난방 기준을 미리 설정했다" } },
        { role: "featureBullet", text: { en: "반복 의사결정을 자동화", ko: "반복 의사결정을 자동화" } },
        { role: "featureBullet", text: { en: "매번 새로 판단할 필요 없음", ko: "매번 새로 판단할 필요 없음" } },
        { role: "resultLabel", text: { en: "결과", ko: "결과" } },
        { role: "resultBody", text: { en: "매번 결정 → 설정 기반 자동 운영", ko: "매번 결정 → 설정 기반 자동 운영" } },
        { role: "image", src: "/projects/operator/solution/mockup-overview.jpg", alt: "Mockup Overview" },
        { role: "subLabel", text: { en: "Flow Change", ko: "플로우 변화" } },
        { role: "h3", text: { en: "From repeated adjustments to a single judgment", ko: "반복 조정에서 단 한 번의 판단으로" } },
        { role: "flowLabel", text: { en: "BEFORE", ko: "BEFORE" } },
        { role: "flowStep", text: { en: "정보 확인", ko: "정보 확인" } },
        { role: "flowStep", text: { en: "해석", ko: "해석" } },
        { role: "flowStep", text: { en: "선택", ko: "선택" } },
        { role: "flowStep", text: { en: "반복", ko: "반복" } },
        { role: "flowLabel", text: { en: "AFTER", ko: "AFTER" } },
        { role: "flowStep", text: { en: "상태 확인", ko: "상태 확인" } },
        { role: "flowStep", text: { en: "선택", ko: "선택" } },
        { role: "flowStep", text: { en: "완료", ko: "완료" } },
        { role: "subLabel", text: { en: "KPI & Impact", ko: "KPI & 임팩트" } },
        { role: "h3", text: { en: "Improving decision-making structure directly impacts operational efficiency and cost", ko: "의사결정 구조 개선은 운영 효율과 비용에 직접적인 영향을 준다" } },
        { role: "kpiLabel", text: { en: "USER IMPACT", ko: "USER IMPACT" } },
        { role: "featureBullet", text: { en: "의사결정 시간 감소", ko: "의사결정 시간 감소" } },
        { role: "featureBullet", text: { en: "반복 조정 횟수 감소", ko: "반복 조정 횟수 감소" } },
        { role: "featureBullet", text: { en: "판단 피로 감소", ko: "판단 피로 감소" } },
        { role: "kpiLabel", text: { en: "BUSINESS IMPACT", ko: "BUSINESS IMPACT" } },
        { role: "featureBullet", text: { en: "불필요한 냉난방 사용 감소", ko: "불필요한 냉난방 사용 감소" } },
        { role: "featureBullet", text: { en: "에너지 비용 절감", ko: "에너지 비용 절감" } },
        { role: "featureBullet", text: { en: "매장 환경 일관성 향상", ko: "매장 환경 일관성 향상" } },
        { role: "kpiLabel", text: { en: "EXPECTED KPI", ko: "EXPECTED KPI" } },
        { role: "kpiDesc", text: { en: "% 판단 시간 단축", ko: "% 판단 시간 단축" } },
        { role: "kpiDesc", text: { en: "% 반복 조작 빈도 감소", ko: "% 반복 조작 빈도 감소" } },
        { role: "kpiDesc", text: { en: "% 에너지 비용 절감 가능성", ko: "% 에너지 비용 절감 가능성" } },
        { role: "kpiLabel", text: { en: "BEHAVIORAL CHANGE", ko: "BEHAVIORAL CHANGE" } },
        { role: "kpiLabel", text: { en: "BEFORE", ko: "BEFORE" } },
        { role: "kpiLabel", text: { en: "AFTER", ko: "AFTER" } },
        { role: "subLabel", text: { en: "Outcome", ko: "결과" } },
        { role: "h3", text: { en: "We designed a UT protocol to validate the HVAC decision-making flow", ko: "UT 프로토콜을 설계하고, 이를 기반으로 냉난방 의사결정 흐름을 검증했다" } },
        { role: "body", text: { en: "We designed a UT protocol based on scenarios reflecting real store operations, to observe how users judge and select HVAC options. The protocol tracked three key metrics: decision speed, comprehension of the proposed choice, and confusion during the selection process — recording behavior and decision-making at each step.", ko: "실제 매장 운영 상황을 반영한 시나리오를 바탕으로 사용자가 냉난방을 어떻게 판단하고 선택하는지 검증하기 위해 UT 프로토콜을 설계했다. 프로토콜에서는 판단 속도, 제안된 선택의 이해도, 선택 과정에서의 혼란 여부를 주요 지표로 설정하고, 각 단계에서의 행동과 의사결정 과정을 기록했다." } },
        { role: "body", text: { en: "SUS score — confirming usability above the acceptable threshold.", ko: "SUS 점수 — 사용성 기준을 상회하는 결과를 확인했다." } },
        { role: "image", src: "/projects/operator/validate/usability-test.jpg", alt: "Usability Test" },
        { role: "image", src: "/projects/operator/validate/ut-protocol.jpg", alt: "UT Protocol" },
        { role: "image", src: "/projects/operator/validate/sus-score.jpg", alt: "SUS Validated Usability Through SUS" },
        { role: "h3", text: { en: "Users shifted from a pattern of adjusting and checking to making a single judgment and selecting", ko: "사용자는 냉난방을 '조정하며 확인'하던 방식에서, 한 번의 판단으로 선택하는 방식으로 전환되었다" } },
        { role: "body", text: { en: "Testing showed that users no longer made multiple adjustments as before — instead, they reviewed the proposed choice directly and made a decision. Hesitation during the judgment process decreased, and confidence in selections increased. The SUS score of 76 confirmed usability above the acceptable threshold.", ko: "테스트 결과, 사용자는 기존처럼 여러 번 조정하지 않고 제안된 선택을 바로 확인하고 결정하는 흐름을 보였다. 또한, 판단 과정에서의 망설임이 줄어들고 선택에 대한 확신이 높아지는 경향이 나타났다. SUS 76점으로 사용성 기준을 상회하는 결과를 확인했다." } },
      ],
    },
    {
      id: "iteration",
      blocks: [
        { role: "groupLabel", text: { en: "Iteration", ko: "반복" } },
        { role: "subLabel", text: { en: "Insight & Iteration", ko: "인사이트 & 개선" } },
        { role: "h2", text: { en: "Testing Showed Where the Structure Still Got in the Way", ko: "테스트에서 구조가 아직 방해가 되는 곳이 드러났다" } },
        { role: "body", text: { en: "The first version revealed two structural issues — both about flow. Places where small business owners had to break their thinking to navigate the interface.", ko: "첫 번째 버전에서 두 가지 구조적 문제가 드러났다 — 둘 다 흐름에 관한 것이었다. 자영업자가 인터페이스를 탐색하기 위해 생각을 끊어야 하는 곳." } },
        { role: "cardLabel", text: { en: "Iteration 01", ko: "반복 01" } },
        { role: "cardTitle", text: { en: "To keep the judgment flow intact, we reduced screen transitions and consolidated actions into a single context", ko: "판단 흐름이 끊기지 않도록, 화면 전환을 줄이고 하나의 맥락으로 통합했다" } },
        { role: "cardBody", text: { en: "In the original structure, completing a single decision required navigating across multiple screens — breaking the judgment flow in the process. To fix this, we consolidated related actions into a single screen so the decision process could flow without interruption.", ko: "기존 구조에서는 하나의 결정을 완료하기 위해 여러 화면을 이동해야 했고, 이 과정에서 판단 흐름이 끊기는 문제가 발생했다. 이를 개선하기 위해 관련된 행동을 하나의 화면 안에서 처리할 수 있도록 통합해, 결정 과정이 자연스럽게 이어지도록 재구성했다." } },
        { role: "cardLabel", text: { en: "Iteration 02", ko: "반복 02" } },
        { role: "cardTitle", text: { en: "We moved the 'outcome' — what users look for first — to the top of the screen", ko: "자영업자가 가장 먼저 확인하는 '결과'를 상단으로 이동시켰다" } },
        { role: "cardBody", text: { en: "In the initial layout, expected outcomes (comfort and cost) were placed at the bottom. Testing revealed that users immediately wanted to know 'what will actually happen' upon opening the app. Based on this, we moved outcome information to the top — redesigning the flow so users see the result first, then proceed to make a choice.", ko: "초기 레이아웃에서는 예상 결과(쾌적도·비용)가 하단에 위치해 있었지만, 테스트를 통해 사용자는 앱을 열자마자 '그래서 어떻게 되는지'를 먼저 확인하려는 경향을 보였다. 이에 따라 결과 정보를 최상단으로 이동시켜, 사용자가 결과를 먼저 확인하고 → 선택으로 이어지는 흐름으로 재설계했다." } },
      ],
    },
    {
      id: "reflection",
      blocks: [
        { role: "groupLabel", text: { en: "Reflection", ko: "회고" } },
        { role: "reflectTitle", text: { en: "How you define the problem determines every design decision that follows", ko: "문제를 어떻게 정의하느냐가, 이후 모든 설계를 결정한다" } },
        { role: "reflectBody", text: { en: "We initially approached this as an HVAC control problem. Research revealed that the issue wasn't about operation — it was a structure where users couldn't make a judgment about what to do. Shifting that frame redirected us from designing features to designing a judgment flow. What to leave out became clearer than what to build.", ko: "초기에는 HVAC 제어 문제로 접근했다. 하지만 리서치를 통해, 문제는 조작이 아니라 '무엇을 해야 하는지 판단할 수 없는 구조'에 있다는 것을 확인했다. 이 프레임을 바꾸면서 기능이 아니라 판단 흐름을 설계하는 방향으로 전환되었고, 무엇을 만들지보다 무엇을 만들지 않을지가 더 명확해졌다." } },
        { role: "reflectTitle", text: { en: "Data only has meaning when it leads to a decision", ko: "데이터는 '결정으로 이어질 때'만 의미를 가진다" } },
        { role: "reflectBody", text: { en: "Operators already had access to temperature, usage, and cost data. But none of it was connected to the outcome of each choice — making it impossible to use in actual decision-making. This project taught us that the problem wasn't a lack of data, but a structure that failed to link choices to results.", ko: "운영자는 이미 온도, 사용량, 비용 데이터를 확인할 수 있었다. 하지만 각 선택이 어떤 결과를 만드는지 연결되지 않아 실제 판단에는 활용되지 못하고 있었다. 이 프로젝트를 통해 문제는 데이터의 유무가 아니라, 선택과 결과를 연결하지 못하는 구조에 있다는 것을 배웠다." } },
        { role: "reflectTitle", text: { en: "Users struggle more with deciding than with acting", ko: "사용자는 행동보다 '결정'을 어려워한다" } },
        { role: "reflectBody", text: { en: "Existing systems were designed to let users operate the controls. But in practice, the harder challenge wasn't how to adjust — it was deciding what to choose at all. Understanding this difference shifted our approach: instead of helping users judge, we designed a structure where the system judges first and the user approves.", ko: "기존 시스템은 사용자가 조작할 수 있도록 설계되어 있었다. 하지만 실제 운영에서는 어떻게 조작할지보다 무엇을 선택해야 하는지 결정하는 것 자체가 더 어려운 문제였다. 이 차이를 이해한 이후, 사용자가 판단하도록 돕는 것이 아니라 시스템이 먼저 판단하고, 사용자는 승인하는 구조로 접근하게 되었다." } },
        { role: "reflectTitle", text: { en: "Simplifying the judgment flow matters more than adding features", ko: "기능을 추가하는 것보다, 판단 흐름을 단순화하는 것이 더 중요하다" } },
        { role: "reflectBody", text: { en: "We could have added more features — but we deliberately removed anything that clouded the judgment flow. By reducing the steps between reviewing information, interpreting it, and selecting, and by integrating status, outcome, and choice into a single screen, we compressed the decision-making process. The result: users could make a choice with a single judgment instead of repeated adjustments.", ko: "여러 기능을 추가할 수 있었지만, 판단 흐름을 흐리는 요소는 의도적으로 제거했다. 특히 정보 확인 → 해석 → 선택으로 이어지는 단계를 줄이고, 상태·결과·선택을 한 화면에 통합하는 방식으로 의사결정 과정을 압축했다. 그 결과, 사용자는 여러 번 조정하는 대신 한 번의 판단으로 선택할 수 있게 되었다." } },
        { role: "reflectTitle", text: { en: "Reducing scope isn't about giving up features — it's about making judgment clearer", ko: "범위를 줄이는 것은 기능을 포기하는 것이 아니라, 판단을 명확하게 만드는 과정이다" } },
        { role: "reflectBody", text: { en: "In designing the MVP, we chose to include only the features directly needed for decision-making rather than everything possible. The features we cut made the remaining ones clearer in both role and flow — resulting in a structure where users could make faster, more confident decisions.", ko: "MVP를 설계하며 모든 기능을 포함하는 대신, 의사결정에 직접적으로 필요한 기능만 남기는 것을 선택했다. 이 과정에서 제거된 기능들은 남은 기능의 역할과 흐름을 더 명확하게 만들었고, 결과적으로 사용자가 더 빠르게 판단할 수 있는 구조로 이어졌다." } },
      ],
    },
  ],
};
